      integer fftw_r2hc
      parameter (fftw_r2hc=0)
      integer fftw_hc2r
      parameter (fftw_hc2r=1)
      integer fftw_dht
      parameter (fftw_dht=2)
      integer fftw_redft00
      parameter (fftw_redft00=3)
      integer fftw_redft01
      parameter (fftw_redft01=4)
      integer fftw_redft10
      parameter (fftw_redft10=5)
      integer fftw_redft11
      parameter (fftw_redft11=6)
      integer fftw_rodft00
      parameter (fftw_rodft00=7)
      integer fftw_rodft01
      parameter (fftw_rodft01=8)
      integer fftw_rodft10
      parameter (fftw_rodft10=9)
      integer fftw_rodft11
      parameter (fftw_rodft11=10)
      integer fftw_forward
      parameter (fftw_forward=-1)
      integer fftw_backward
      parameter (fftw_backward=+1)
      integer fftw_measure
      parameter (fftw_measure=0)
      integer fftw_destroy_input
      parameter (fftw_destroy_input=1)
      integer fftw_unaligned
      parameter (fftw_unaligned=2)
      integer fftw_conserve_memory
      parameter (fftw_conserve_memory=4)
      integer fftw_exhaustive
      parameter (fftw_exhaustive=8)
      integer fftw_preserve_input
      parameter (fftw_preserve_input=16)
      integer fftw_patient
      parameter (fftw_patient=32)
      integer fftw_estimate
      parameter (fftw_estimate=64)
      integer fftw_estimate_patient
      parameter (fftw_estimate_patient=128)
      integer fftw_believe_pcost
      parameter (fftw_believe_pcost=256)
      integer fftw_dft_r2hc_icky
      parameter (fftw_dft_r2hc_icky=512)
      integer fftw_nonthreaded_icky
      parameter (fftw_nonthreaded_icky=1024)
      integer fftw_no_buffering
      parameter (fftw_no_buffering=2048)
      integer fftw_no_indirect_op
      parameter (fftw_no_indirect_op=4096)
      integer fftw_allow_large_generic
      parameter (fftw_allow_large_generic=8192)
      integer fftw_no_rank_splits
      parameter (fftw_no_rank_splits=16384)
      integer fftw_no_vrank_splits
      parameter (fftw_no_vrank_splits=32768)
      integer fftw_no_vrecurse
      parameter (fftw_no_vrecurse=65536)
      integer fftw_no_simd
      parameter (fftw_no_simd=131072)
